#!/bin/sh

# Initalise le fichier "AirQualityWAtch.json" à partir des données téléchargées dans les fichiers "AirQualityWAtch-YYYY-MM-DDTHH:MM:MM:SS.XXXZ.json" présents dans le répertoire courant

# "AirQualityWAtch.json" sera utilisé pour générer le curveChart

dirName="datas"
fileName="AirQualityWatch"


if [ -f "$dirName/$fileName.json" ] ; then
	mv "$dirName/$fileName.json" "$dirName/$fileName.bak.json" 
fi

echo "[" > "$dirName/$fileName.json"

premier=1

for i in $dirName/$fileName-*.json ; do
	echo "Processing $i"
	if [ $premier -eq 1 ] ; then
		premier=0
	else
		echo "," >> "$dirName/$fileName.json"
	fi
	cat "$i" >> "$dirName/$fileName.json"
	
done

echo "]" >> $dirName/$fileName.json
	
	
