#!/bin/sh

# Initalise le fichier "AirQualityWAtch.json" à partir des données téléchargées dans les fichiers "AirQualityWAtch-YYYY-MM-DDTHH:MM:MM:SS.XXXZ.json" présents dans le répertoire courant

# "AirQualityWAtch.json" sera utilisé pour générer le curveChart


fileName = "AirQualityWAtch.json"

if [ -f "$fileName.json" ] ; then
	mv "$fileName.json" "$fileName.bak.json" 
fi

echo "[" > "$fileName.json"

for i in "$fileName-*.json" ; do
	echo "Processing $i"
	cat "$i" >> "$fileName.json"
done

echo "]" >> 
	
	
